### ISSUE TITLE
Default colors for ride tracks and vehicles

### ISSUE THREAD

**Issue by spacek531** [spacek531/RCT1Vehicles#17]
It would be nice to know the default colors of RCT1 vehicles and ride types, although the latter is not so critical as most of the ride types can be reused from RCT2.

**Comment by spacek531** [comment]
@ZeeMajora Are you satisfied with the default colors of all the rides currently? If so, I will close this issue.

**Comment by ZeeMaji** [comment]
For the vehicles? Yeah they should all be correct at this point.
For the tracks? I think they're alright at the moment as i don't think there was many changes to the default track colors across 1 and 2, also i feel that is more of a main openrct2 issue than something pertaining to this project anyhow.
So feel free to close this.

**Comment by ZeeMaji** [comment]
This is complete and can be closed.
