### ISSUE TITLE
RCT2 Fallback Images

### ISSUE THREAD

**Issue by ZeeMaji** [spacek531/RCT1Vehicles#42]
In the official OpenRCT2 objects repo, many of the RCT1 objects have secondary image tables called "noCsgImages" that are loaded if the user does not have RCT1 linked to OpenRCT2 that use images available from the RCT2 base game objects/g1.dat to prevent graphical glitches.
We should work on implementing these for our RCT1 objects here, especially should they be implemented into OpenRCT2 officially as without them they will look like a garbled mess of graphics if the user does not have RCT1 linked.

For most of the objects direct counterparts exist in RCT2 to get fallback images from, but for some it may be a bit more tricky as they do not have counterparts or their counterparts have missing sprites.

**Comment by spacek531** [comment]
I think the only place RCT1 has more sprite groups than the equivalent RCT2 vehicle is the junior coaster, right?

**Comment by ZeeMaji** [comment]
Currently, yes.

**Comment by spacek531** [comment]
Fall back images:
- [x] rct1.ride.bobsleigh_trains
- [x] rct1.ride.bumper_boats
- [x] rct1.ride.cat_cars
- [x] rct1.ride.chairlift_cars
- [x] rct1.ride.corkscrew_trains
- [x] rct1.ride.corkscrew_trains_reversed
- [x] rct1.ride.dinghies
- [x] rct1.ride.dodgems
- [x] rct1.ride.go_karts
- [x] rct1.ride.horses
- [x] rct1.ride.inverted_trains
- [x] rct1.ride.logs
- [x] rct1.ride.mine_cars
- [x] rct1.ride.mine_trains
- [x] rct1.ride.minilady
- [x] rct1.ride.minilog
- [x] rct1.ride.minirock
- [x] rct1.ride.motorbikes
- [x] rct1.ride.mouse_cars
- [x] rct1.ride.pickup_trucks
- [x] rct1.ride.racing_cars
- [x] rct1.ride.reverse_freefall_car
- [x] rct1.ride.single_person_swinging_cars
- [x] rct1.ride.small_monorail_cars
- [x] rct1.ride.sports_cars
- [x] rct1.ride.stand_up_trains
- [x] rct1.ride.steam_trains
- [x] rct1.ride.steel_rc_trains
- [x] rct1.ride.steel_rc_trains_reversed
- [x] rct1.ride.streamlined_monorail_trains
- [x] rct1.ride.suspended_swinging_aeroplane_cars
- [x] rct1.ride.suspended_swinging_cars
- [x] rct1.ride.swinging_lay_down_cars
- [x] rct1.ride.vertical_drop_trains
- [x] rct1.ride.wooden_rc_trains
- [x] rct1.ride.wooden_rc_trains_reversed
- [x] rct1aa.ride.bicycles
- [x] rct1aa.ride.floorless_twister_trains
- [x] rct1aa.ride.flying_saucers
- [x] rct1aa.ride.ghost_train_cars
- [x] rct1aa.ride.heartline_twister_cars
- [x] rct1aa.ride.heartline_twister_cars_reversed
- [x] rct1aa.ride.hyper_twister_trains
- [x] rct1aa.ride.mini_helicopters
- [x] rct1aa.ride.reverser_cars
- [x] rct1aa.ride.side_friction_cars - WIP
- [x] rct1aa.ride.ski_lift_cars
- [x] rct1aa.ride.splash_boats
- [x] rct1aa.ride.stand_up_twister_trains
- [x] rct1aa.ride.steam_trains_covered
- [x] rct1aa.ride.steel_wild_mouse_cars
- [x] rct1aa.ride.suspended_monorail_trains
- [x] rct1aa.ride.twister_trains
- [x] rct1aa.ride.vintage_cars
- [x] rct1aa.ride.wooden_articulated_trains
- [x] rct1ll.ride.4_across_inverted_trains
- [x] rct1ll.ride.air_powered_trains
- [x] rct1ll.ride.coaster_boats
- [x] rct1ll.ride.face_off_cars
- [x] rct1ll.ride.hypercoaster_trains
- [x] rct1ll.ride.inverted_hairpin_cars
- [x] rct1ll.ride.jet_skis
- [x] rct1ll.ride.rafts
- [x] rct1ll.ride.steam_trains_american
- [x] rct1ll.ride.steam_trains_american_uncovered
- [ ] (Laydown coaster)
- [ ] (Virginia reel)
- [ ] (steel spinning)
- [ ] (river rapids)

**Comment by ZeeMaji** [comment]
I can go ahead and close this issue if you'd like as it's basically done, when i eventually add the experimental objects to this repo i will add them with the fallback images there from the start.

**Comment by ZeeMaji** [comment]
Asides from the spinning cars which will be done when i finish the object once it's able to be ported properly, every other object's fallbacks are done. So this can now be closed.
