### ISSUE TITLE
Hypercoaster second car guest sprites messed up on diagonal slopes

### ISSUE THREAD

**Issue by ZeeMaji** [spacek531/RCT1Vehicles#46]
A bug within RCT1 itself, there are incorrect sprites in the second car's guest sprites on slopes8Banked22
![unknown](https://user-images.githubusercontent.com/42477864/166848121-8987e7fa-6515-4716-a6fd-b5294c7f93e1.png)
![unknown (1)](https://user-images.githubusercontent.com/42477864/166848123-83427039-bfc7-4f87-8f5e-8cb28ea0da5c.png)
![rct1](https://user-images.githubusercontent.com/42477864/166848154-ed4ac42d-67bb-4114-878e-4c1a8ed68b3e.png)
These should be fixable by re-arranging the improperly arranged sprites.

**Comment by spacek531** [comment]
RCT1 has this bug?

Edit: oh I see

the second pic does not appear to be slopes8banked22, are there two issues or is it a diff sprite group?

it's possible the correct sprite doesn't even exist - there's at least one instance of sprites being messed up in RCT2

**Comment by ZeeMaji** [comment]
I accidentally said slopes8banked22 when i wrote the issue initially i just meant regular diagonal inclines, of which these seem to be the 50 degree downwards sprites.
I believe that the sprites were just accidentally swapped somehow in rct1's development, as the guest sprites in the first screenshot would probably fit in the second screenshot, and the second screenshot's invisible sprite would make since in the first screenshot as the guests probably are not visible.
So fixing it should just be a matter of finding the problematic sprites and swapping them around in the order, hopefully.
