### ISSUE TITLE
RCT1 ratingMultiplier Values

### ISSUE THREAD

**Issue by ZeeMaji** [spacek531/RCT1Vehicles#52]
RCT1 seems to have ratingMultiplier values much like RCT2 however they are hidden and not shown on the vehicle tab.
Here is a comparison of woodchip in RCT1 running with normal cars, and another one with reversed cars.
![unknown](https://user-images.githubusercontent.com/42477864/168575488-8eb4a9f3-5b9d-4a4f-a66c-26dce1153dfb.png)

We should figure out a way to either extract these values from RCT1 or determine them with math by comparing stats between different trains in RCT1 itself.

**Comment by SpartanFrederic104** [comment]
From this picture, I can determine that the reversed wooden coaster trains have a +2% excitement factor boost, a +13% intensity factor boost, and a +24%/+25% nausea factor boost.

**Comment by SpartanFrederic104** [comment]
Now I wonder what the stat comparison on a Steel Roller Coaster with both of its available train types would be. It would likely be similar to this too.

**Comment by ZeeMaji** [comment]
I did do some testing with that a while back, my results were inconsistent with what ratingmultiplier numbers i had to put in the openrct2 object to get the same stats on a specific design. Here's two examples from testing some RCT1 pre-builts.

For exterminator it took these values to get the ratings to match up in openrct2 with the original design in RCT1
        "ratingMultipler": {
            "excitement": 2,
            "intensity": 15,
            "nausea": 30
        },
But for shuttle loop it took these very different values to get the ratings to match up in openrct2 with the original design in RCT1
        "ratingMultipler": {
            "excitement": 2,
            "intensity": 25,
            "nausea": 65
        },

The numbers needed are just so radically different, i think RCT1 might be using different calculations from RCT2 entirely for it's rating multipliers.

**Comment by SpartanFrederic104** [comment]
That's what I was suspecting as well.

**Comment by ZeeMaji** [comment]
Personally i was thinking it would be fine if we just use a "close enough" value if the ratingmultiplier calculations between the two games are indeed different as there are a lot of other calculation differences between rct1, rct2, and open that i don't think absolute 100% accuracy for this is absolutely needed seeing as many other things are already going to cause stat differences (eg: rct1 doesn't seem to have an air time stat and excitement bonus from it)
For the steel reversed trains i was thinking the exterminator rating multiplier values would be good as they're pretty in line with rct2's rating multipliers (reversed 6 seater wooden trains come to mind) as the shuttle loop values are pretty absurd by rct2 standards.

**Comment by ZeeMaji** [comment]
Gymnasiast has went ahead and given us the ok to use close enough values for the ratingmultipliers for these vehicles so being absolutely accurate to rct1 in regards to these is not needed.

**Comment by ZeeMaji** [comment]
Implemented in official objects repo.
