### ISSUE TITLE
Swinging suspended plane cars (rct1.ride.arrsw2) have bad diagonal incline sprites

### ISSUE THREAD

**Issue by ZeeMaji** [spacek531/RCT1Vehicles#54]
The last two swinging sprites for the diagonal incline sets in each direction of the swinging plane cars are messed up.
They seem to have been swapped, and the second to last (now last) frame has been replaced with a strange circle.
Comparison between the 8 degree sprites for the plane cars and normal swinging cars showcase this.
![plane1](https://user-images.githubusercontent.com/42477864/169655879-3d546185-c1d7-4d2f-b3fe-38b34133466e.png)

In the game itself, it has this effect on the cars (note the one car swinging in the opposite direction to the others in the first screenshot)
![plane2](https://user-images.githubusercontent.com/42477864/169655944-ee995e41-b8f0-41c0-be81-70d8528f1f52.png)
![plane4](https://user-images.githubusercontent.com/42477864/169656834-375bca3b-e948-48df-96e3-d5287689a671.png)

This even happens in RCT1 as well.
![plane3](https://user-images.githubusercontent.com/42477864/169655984-beebcd71-fee7-4c44-85b7-f5431d18f919.png)

Fixing one of the sprites seems easily doable as the problematic sprites just need to be swapped in the object's image table, but the other ones (the ones that would be where the weird circles are) do not appear to exist anywhere in csg (not even in the base game's csg as this issue is there as well)

**Comment by spacek531** [comment]
I think you mentioned the last two swing sprites of every vehicle angle were missing, right? If so, the resolution is to use the last two non-missing sprites like you did for the bobsled.

**Comment by ZeeMaji** [comment]
For the swinging suspended cars the swinging frame count is the same between rct1 and rct2 (7 frames) so there were no issues in regards to that.
For these specifically we have one of the frames for the last two swinging sprites but the other one is missing.
Do you think it would be fine if we used the one sprite we have access to and then replace the remaining missing sprite with the last non-missing sprite for it's swinging direction even if the swinging angle will be different between the two directions?
If not then we can just ignore the remaining sprite and use the last two swinging sprites like i did for the bobsleigh like you said.

**Comment by spacek531** [comment]
I like your suggestion, lets do it.
