### ISSUE TITLE
More descriptive object names

### ISSUE THREAD

**Issue by spacek531** [spacek531/RCT1Vehicles#56]
Official OpenRCT2 vehicles are getting long names according to this comment: https://github.com/OpenRCT2/objects/pull/166#issuecomment-1140238893

I think this project is similar in that we are creating names for RCT1 rides. Yes, there are RCT2 versions for most RCT1 rides, but I think the OpenRCT2 long format names should be addressed for this project.

Currently we have a mix of RCT2 names (the ride's name not the full namespace) and new names, following the RCT2 name format.

RCT2 names e.g. rct1aa.ride.bmfl, rct1ll.ride.rftboat

New names e.g. rct1.ride.spcar, rct1.ride.minilady

@gymnasiast what are your opinions on the object ids in this PR?

**Comment by SpartanFrederic104** [comment]
I came up with my ideas for the more descriptive RCT1 object names (with this I also came up with my own new object naming convention for ride objects: **_source game.ride.ride_type.extra_description_**):
- rct1.ride.arrsw1 → **rct1.ride.suspended_swinging_rc**
- rct1.ride.arrsw2 → **rct1.ride.suspended_swinging_rc.plane**
- rct1.ride.bboat → **rct1.ride.car_ride.bumper_boat**
- rct1.ride.bmvd → **rct1.ride.vertical_drop_rc**
- rct1.ride.bob → **rct1.ride.bobsleigh_rc**
- rct1.ride.clift1 → **rct1.ride.chairlift**
- rct1.ride.corkrc → **rct1.ride.corkscrew_rc**
- rct1.ride.corkrcrv → **rct1.ride.corkscrew_rc.rev**
- rct1.ride.ctcar → **rct1.ride.car_ride.cheshire_cats**
- rct1.ride.cwood → **rct1.ride.wooden_rc**
- rct1.ride.cwoodrv → **rct1.ride.wooden_rc.rev**
- rct1.ride.dinghy → **rct1.ride.dinghy_slide**
- rct1.ride.gioinv → **rct1.ride.inverted_rc.gioinv**
- rct1.ride.horses → **rct1.ride.steeplechase.horses**
- rct1.ride.karts → **rct1.ride.go_karts**
- rct1.ride.lfb → **rct1.ride.log_flume**
- rct1.ride.minetrrc → **rct1.ride.mine_train_rc**
- rct1.ride.minilady → **rct1.ride.classic_mini_rc.ladybird**
- rct1.ride.minilog → **rct1.ride.classic_mini_rc.log**
- rct1.ride.minirock → **rct1.ride.classic_mini_rc.rocket**
- rct1.ride.minispin → **rct1.ride.classic_mini_rc.spinning**
- rct1.ride.monobig → **rct1.ride.monorail.largetrain**
- rct1.ride.monosml → **rct1.ride.monorail.smalltrain**
- rct1.ride.motobike → **rct1.ride.steeplechase.motorbike**
- rct1.ride.msflying → **rct1.ride.mini_suspended_rc.laydown**
- rct1.ride.mswing → **rct1.ride.mini_suspended_rc**
- rct1.ride.nrl1 → **rct1.ride.miniature_railway.steam_train1**
- rct1.ride.rcr → **rct1.ride.car_ride.racing_car**
- rct1.ride.revfall → **rct1.ride.reverse_freefall_rc**
- rct1.ride.spcar → **rct1.ride.car_ride.sports_car**
- rct1.ride.steelrc → **rct1.ride.looping_rc.steel_rc**
- rct1.ride.steelrcrv → **rct1.ride.looping_rc.steel_rc_rev**
- rct1.ride.togst → **rct1.ride.stand_up_rc**
- rct1.ride.truck → **rct1.ride.car_ride.pickup_truck**
- rct1.ride.wmmine → **rct1.ride.wooden_wild_mouse.minecar**
- rct1.ride.wmmouse → **rct1.ride.wooden_wild_mouse.mousecar**
- rct1aa.ride.bmfl → **rct1.ride.twister_rc.floorless**
- rct1aa.ride.bmrb → **rct1.ride.hyper_twister**
- rct1aa.ride.bmsd → **rct1.ride.twister_rc**
- rct1aa.ride.bmsu → **rct1.ride.twister_rc.standup**
- rct1aa.ride.clift2 → **rct1.ride.chairlift.skilift**
- rct1aa.ride.fsauc → **rct1aa.ride.flying_saucers**
- rct1aa.ride.helicar → **rct1aa.ride.mini_helicopters**
- rct1aa.ride.monbk → **rct1aa.ride.monorail_cycles**
- rct1aa.ride.nrl2 → **rct1aa.ride.miniature_railway.steam_train2**
- rct1aa.ride.revcar → **rct1aa.ride.reverser_rc**
- rct1aa.ride.sfric → **rct1aa.ride.side_friction_rc**
- rct1aa.ride.smono → **rct1aa.ride.suspended_monorail**
- rct1aa.ride.smouse → **rct1aa.ride.steel_wild_mouse**
- rct1aa.ride.spboat → **rct1aa.ride.splash_boats**
- rct1aa.ride.utcar → **rct1aa.ride.heartline_twister_rc**
- rct1aa.ride.utcarrv → **rct1aa.ride.heartline_twister_rc.rev**
- rct1aa.ride.vcr → **rct1aa.ride.car_ride.vintage_car**
- rct1aa.ride.vreel → **rct1aa.ride.virginia_reel**
- rct1aa.ride.woodtrc → **rct1aa.ride.wooden_rc.twister**
- rct1ll.ride.airpower → **rct1ll.ride.air_powered_vertical_rc**
- rct1ll.ride.aml1 → **rct1ll.ride.miniature_railway.american_steam_train1**
- rct1ll.ride.aml2 → **rct1ll.ride.miniature_railway.american_steam_train2**
- rct1ll.ride.arrhyper → **rct1ll.ride.hypercoaster**
- rct1ll.ride.cstboat → **rct1ll.ride.water_coaster**
- rct1ll.ride.faceoff → **rct1ll.ride.compact_inverted_rc.faceoff**
- rct1ll.ride.invhairp → **rct1ll.ride.inverted_hairpin_rc**
- rct1ll.ride.jski → **rct1ll.ride.boat_hire.jetski**
- rct1ll.ride.nemt → **rct1ll.ride.inverted_rc.4s**
- rct1ll.ride.rftboat → **rct1ll.ride.river_rafts**

Only the Dodgems remains unchanged.

**Comment by Gymnasiast** [comment]
Our convention is to have the dot separate the source game, type and name, and use only the underscore as a separator within these groups.
