### ISSUE TITLE
Dummy OriginalId

### ISSUE THREAD

**Issue by spacek531** [spacek531/RCT1Vehicles#63]
To allow for saving of track designs, dummy OriginalId are required. See this PR for details https://github.com/OpenRCT2/objects/commit/3de5537a848db5770fb97642077dde4fb37f0b42

**Comment by SpartanFrederic104** [comment]
For rct1.ride.gioinv (as an example), a dummy `originalId` field can be as follows: `"originalId": "00000000|#RCT1GIO|00000000"`
