### ISSUE TITLE
Reverser script cannot reverse fallback style image tables

### ISSUE THREAD

**Issue by ZeeMaji** [spacek531/RCT1Vehicles#65]
When attempting to use the reverser script to reverse fallback style image tables where every other sprite number is skipped, the order gets messed up.
I did this by just renaming the "noCsgImages" to "images" and removing the original "images" table, i also went ahead and removed any numbers from image table text (eg: "$RCT2:OBJDATA/SCHT1.DAT[3]", to "$RCTTWO:OBJDATA/SCHTONE.DAT[3]", to eliminate that being the issue.

**Comment by ZeeMaji** [comment]
This isn't exactly required any more for this project's vehicles as i have semi-manually done the fallback sprites for the reversed steel train and those should be mostly re-usable for the reversed wooden trains but i'll leave this open as it is an issue with the ordermantools script included in this repo.

**Comment by spacek531** [comment]
Fixed.
