### ISSUE TITLE
Slightly incorrect image dimensions for Wooden Mouse Cars preview image

### ISSUE THREAD

**Issue by SpartanFrederic104** [spacek531/RCT1Vehicles#87]
![preview](https://user-images.githubusercontent.com/61885939/197349413-15c0da88-4dec-403e-befb-0af9551ef14b.png)
I checked the image dimensions for the Wooden Wild Mouse's Mouse Cars preview image and they are **111×112** instead of the standard **112×112** that preview images always have.

**Comment by ZeeMaji** [comment]
This can be closed as the issue was fixed in #89
