### ISSUE TITLE
Accidental LL path railing & incorrect resolution in suspended swinging train thumbnail

### ISSUE THREAD

**Issue by ZeeMaji** [spacek531/RCT1Vehicles#93]
There is a yellow bamboo path railing visible in the suspended swinging train's thumbnail in the top left corner, it should either be changed to the wooden railings or the queue should be removed entirely from the thumbnail frame the latter of which would be more accurate to the original thumbnail.
The thumbnail is also the wrong resolution as it is 111x112 instead of 112x112.

![Screenshot_select-area_20221122200913](https://user-images.githubusercontent.com/42477864/203451420-a50cfe00-7c35-4008-a334-fe13eb8c854c.png)

**Comment by SpartanFrederic104** [comment]
The Wooden Mouse Cars thumbnail also has the same issue of 111x112 instead of being 112x112 (#87).

**Comment by ZeeMaji** [comment]
Fixed in the official objects repo.
